# Generated by Django 6.0.5 on 2026-05-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en stock')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó el producto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
